### ISSUE TITLE
Modifiers as an object

### ISSUE THREAD

**Issue by igoradamenko** [vitkarpov/bem_#2]
Hi!

I didn't use your library, but it seems like good idea. `m` can use first param like an object: `{mod1: val1, mod2: val2}` (like `mods` in BEMJSON). I think this:

```
b.e('button').m({
    size: 'xl',
    type: 'submit',
    theme: 'islands',
    disabled: true
});
```

..is better than this:

```
b.e('button').m('size', 'xl').m('type'. 'submit').m('theme', 'islands').m('disabled');
```

But may be the main idea of this lib is an only chain interface and then my idea is not so good.

**Comment by vitkarpov** [comment]
If you're more familiar with the bemjson-like interface, check out [`b_`](https://www.npmjs.com/package/b_). Seem chains are enough for a while.
