### ISSUE TITLE
Автоматический микс с элементом другого блока

### ISSUE THREAD

**Issue by vitkarpov** [vitkarpov/bem_#3]
Хочется смиксовать элемент блока от родительской вьюшки к блоку дочерней вьюшки, чтобы доопределить поведение. Сейчас это делается так:

В родительской вьюшке:

``` js
this.createChildren('foo', {
  className: this.b.e('hello')
})
```

в дочерней `foo`:

``` js
<div className={this.b + ' ' + this.props.className} />
```

Хочется, чтобы `this.b` автоматически смотрел на `className` в пропсах текущего экземпляра и добавлял его к себе — получится автоматический микс элемента родительского блока на текущий блок.

Как идея?

**Comment by vitkarpov** [comment]
@i2r @km256 @alexeyten @iegit

**Comment by i2r** [comment]
👍 Правильная идея, миксин так и должен работать.

**Comment by vitkarpov** [comment]
https://github.com/vitkarpov/bem_/pull/4

**Comment by vitkarpov** [comment]
Done
